create database if not exists sancks;
use sancks;
CREATE TABLE IF NOT EXISTS `商品资料` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `名称` VARCHAR(255) NOT NULL,
  `分类` VARCHAR(255) NOT NULL,
  `条码` VARCHAR(255) NOT NULL,
  `规格` VARCHAR(255) NOT NULL,
  `主单位` VARCHAR(255) NOT NULL,
  `库存量` INT NOT NULL,
  `成本` FLOAT NOT NULL,
  `售价` FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS `商品销售流水` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `流水号` VARCHAR(255) NOT NULL,
  `销售时间` DATETIME NOT NULL,
  `会员卡号脱敏` VARCHAR(255) NOT NULL,
  `商品名称` VARCHAR(255) NOT NULL,
  `商品条码` VARCHAR(255) NOT NULL,
  `规格` VARCHAR(255) NOT NULL,
  `单位` VARCHAR(255) NOT NULL,
  `商品分类` VARCHAR(255) NOT NULL,
  `销售数量` INT NOT NULL
);

CREATE TABLE IF NOT EXISTS `采购记录` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `采购单号` VARCHAR(255) NOT NULL,
  `采购时间` DATETIME NOT NULL,
  `供应商` VARCHAR(255) NOT NULL,
  `商品条码` VARCHAR(255) NOT NULL,
  `商品名称` VARCHAR(255) NOT NULL,
  `单位` VARCHAR(255) NOT NULL,
  `规格` VARCHAR(255) NOT NULL,
  `采购量` INT NOT NULL,
  `采购单价` FLOAT NOT NULL
);

